### ISSUE TITLE
Unable to generate pseudo label?

### ISSUE THREAD

**Issue by QiJiawei1** [LiheYoung/ST-PlusPlus#22]
作者你好，我在windos下pycharm复现您代码的时候，无论在VOC还是自己数据集下都无法生成伪标签， pred = Image.fromarray(pred.squeeze(0).numpy().astype(np.uint8), mode='P')会报维度3>2的错误。我的pytorch版本为1.6.0 , python=3.6.13，pillow=8.3.1，numpy=1.16.3，下面是完整信息： 很感激期待您的回复！

Namespace(backbone='resnet101', batch_size=2, crop_size=321, data_root='./ywDataset/', dataset='pascal', epochs=2, labeled_id_path='./dataset/splits/pascal/1_8/split_1/labeled.txt', lr=0.000125, model='deeplabv3plus', plus=None, pseudo_mask_path='./outdir/pseudo_masks/pascal/1_8/split_1', reliable_id_path='./outdir/pseudo_masks/1_8/split_1', save_path='./outdir/models/pascal/1_8/split_1', unlabeled_id_path='./dataset/splits/pascal/1_8/split_1/unlabeled.txt')

================> Total stage 1/3: Supervised training on labeled images (SupOnly)

Params: 59.3M

==> Epoch 0, learning rate = 0.0001					 previous best = 0.00
Loss: 0.712: 100%|██████████| 5/5 [00:44<00:00,  8.92s/it]
mIOU: 33.15: 100%|██████████| 10/10 [00:05<00:00,  1.99it/s]

==> Epoch 1, learning rate = 0.0001					 previous best = 33.15
Loss: 0.589: 100%|██████████| 5/5 [00:42<00:00,  8.56s/it]
mIOU: 33.15: 100%|██████████| 10/10 [00:05<00:00,  1.79it/s]

================> Total stage 2/3: Pseudo labeling all unlabeled images
  0%|          | 0/25 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "D:/ST-PlusPlus-master/main.py", line 359, in <module>
    main(args)
  File "D:/ST-PlusPlus-master/main.py", line 94, in main
    label(best_model, dataloader, args)
  File "D:/ST-PlusPlus-master/main.py", line 331, in label
    pred = Image.fromarray(pred.squeeze(0).numpy().astype(np.uint8), mode='P')
  File "C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\PIL\Image.py", line 2840, in fromarray
    raise ValueError(f"Too many dimensions: {ndim} > {ndmax}.")
ValueError: Too many dimensions: 3 > 2.

**Comment by LiheYoung** [comment]
你好，我们的code是在Linux下测的，你这里应该是由于``pred.squeeze(0)``后的维度依然是三维的，可以打印一下``pred.shape``和``pred.squeeze(0).shape``看一下

**Comment by QiJiawei1** [comment]
> 你好，我们的code是在Linux下测的，你这里应该是由于`pred.squeeze(0)`后的维度依然是三维的，可以打印一下`pred.shape`和`pred.squeeze(0).shape`看一下

打印后显示   pred.shape:torch.Size([2, 256, 256])  ，pred.squeeze(0).shape：torch.Size([2, 256, 256])

**Comment by LiheYoung** [comment]
确认一下是不是修改了这一行[code](https://github.com/LiheYoung/ST-PlusPlus/blob/f4ff2ebaae15fb3e2c6000b50d62a67e40058118/main.py#L150)里的batch_size

**Comment by QiJiawei1** [comment]
> 确认一下是不是修改了这一行[code](https://github.com/LiheYoung/ST-PlusPlus/blob/f4ff2ebaae15fb3e2c6000b50d62a67e40058118/main.py#L150)里的batch_size

十分感谢！ 的确是这里的原因，将batch_size改为1就可以生成伪标签了，但是出现了一个新的问题，3/3阶段和4/6阶段报一样的错误。我在想是不是还是batch_size和num_work的错误，报错如下：

Namespace(backbone='resnet101', batch_size=2, crop_size=321, data_root='./ywDataset/', dataset='pascal', epochs=2, labeled_id_path='./dataset/splits/pascal/1_8/split_1/labeled.txt', lr=0.000125, model='deeplabv3plus', plus=True, pseudo_mask_path='./outdir/pseudo_masks/pascal/1_8/split_1', reliable_id_path='./outdir/pseudo_masks/1_8/split_1', save_path='./outdir/models/pascal/1_8/split_1', unlabeled_id_path='./dataset/splits/pascal/1_8/split_1/unlabeled.txt')

================> Total stage 1/6: Supervised training on labeled images (SupOnly)

Params: 59.3M

==> Epoch 0, learning rate = 0.0001					 previous best = 0.00
Loss: 0.605: 100%|██████████| 5/5 [00:43<00:00,  8.66s/it]
mIOU: 31.92: 100%|██████████| 5/5 [00:04<00:00,  1.17it/s]

==> Epoch 1, learning rate = 0.0001					 previous best = 31.92
Loss: 0.566: 100%|██████████| 5/5 [00:41<00:00,  8.35s/it]
mIOU: 29.13: 100%|██████████| 5/5 [00:03<00:00,  1.28it/s]

================> Total stage 2/6: Select reliable images for the 1st stage re-training
100%|██████████| 10/10 [00:05<00:00,  1.92it/s]

================> Total stage 3/6: Pseudo labeling reliable images
mIOU: 31.66: 100%|██████████| 5/5 [00:14<00:00,  2.95s/it]

================> Total stage 4/6: The 1st stage re-training on labeled and reliable unlabeled images

==> Epoch 0, learning rate = 0.0001					 previous best = 0.00
  0%|          | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:/ST-PlusPlus-master/main.py", line 360, in <module>
    main(args)
  File "D:/ST-PlusPlus-master/main.py", line 159, in main
    best_model = train(model, trainloader, valloader, criterion, optimizer, args)
  File "D:/ST-PlusPlus-master/main.py", line 223, in train
    for i, (img, mask) in enumerate(tbar):
  File "C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 1014, in _process_data
    data.reraise()
  File "C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\torch\_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\ST-PlusPlus-master\dataset\semi.py", line 71, in __getitem__
    img, mask = crop(img, mask, self.size)
  File "D:\ST-PlusPlus-master\dataset\transform.py", line 14, in crop
    mask = ImageOps.expand(mask, border=(0, 0, padw, padh), fill=255)
  File "C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\PIL\ImageOps.py", line 403, in expand
    draw.rectangle((0, 0, width - 1, height - 1), outline=color, width=border)
  File "C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\PIL\ImageDraw.py", line 259, in rectangle
    self.draw.draw_rectangle(xy, ink, 0, width)
TypeError: an integer is required (got type tuple)

**Comment by LiheYoung** [comment]
This might be caused by a mismatched PIL version. Please try ``pip install pillow==8.4.0``.

**Comment by QiJiawei1** [comment]
> This might be caused by a mismatched PIL version. Please try `pip install pillow==8.4.0`.

升级到8.4.0成功解决，十分庆幸您能一直回复我的问题，万分感谢！
